FROM oven/bun:1.3.10-alpine

WORKDIR /app/packages/web

ENV OPENCODE_URL=http://host.docker.internal:4097

COPY --chown=bun:bun packages/web/bin ./bin
COPY --chown=bun:bun packages/web/dist ./dist

USER bun
EXPOSE 3000

CMD ["bun", "bin/cli.js"]
